apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd
  namespace: infrastructor
  annotations:
    kargo.akuity.io/color: "#0c8599"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: infrastructor
    sources:
      stages:
      - qua
  promotionTemplate:
    spec:
      # Variables
      vars:
        - name: frontendImage
          value: ghcr.io/axinorm/infrastructor-frontend
        - name: apiImage
          value: ghcr.io/axinorm/infrastructor-api
        - name: repoURL
          value: ${HELM_REPOSITORY_URL}
      steps:
      # Cloning
      - uses: git-clone
        config:
          repoURL: ${{ vars.repoURL }}
          checkout:
          - branch: main
            path: ./repo
      # Update image tag
      - uses: yaml-update
        as: update-image
        config:
          path: ./repo/values-prd.yaml
          updates:
          - key: frontend.image.tag
            value: ${{ imageFrom(vars.frontendImage).Tag }}
          - key: api.image.tag
            value: ${{ imageFrom(vars.apiImage).Tag }}
      # Commit changes
      - uses: git-commit
        as: commit
        config:
          path: ./repo
          message: |
            chore(kargo): Updating images to ${{ ctx.stage }}
            Frontend image to ${{ imageFrom(vars.frontendImage).Tag }}
            API image to ${{ imageFrom(vars.apiImage).Tag }}
      # Push into a new branch
      - uses: git-push
        as: push
        config:
          path: ./repo
          generateTargetBranch: true
      # Create a Pull Request
      - uses: git-open-pr
        as: open-pr
        config:
          provider: github
          repoURL: ${{ vars.repoURL }}
          sourceBranch: ${{ outputs.push.branch }}
          targetBranch: main
          title: Deploy to ${{ ctx.stage }} environment
          labels: ["application", "needs-review"]
      # Wait until merge
      - uses: git-wait-for-pr
        as: wait-for-pr
        config:
          provider: github
          repoURL: ${{ vars.repoURL }}
          prNumber: ${{ outputs['open-pr'].pr.id }}
      # Update ArgoCD
      - uses: argocd-update
        config:
          apps:
          - name: infrastructor-prd
            namespace: argocd
