# Frontend
frontend:
  replicaCount: 3
  image:
    repository: ghcr.io/axinorm/infrastructor-frontend
    tag: 1.0.0
  service:
    nodePort: 30300

# API
api:
  replicaCount: 3
  image:
    repository: ghcr.io/axinorm/infrastructor-api
    tag: 1.0.0
  service:
    nodePort: 30301
